name: tboxapp
description: The app for a better fitness

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  assets_audio_player: ^2.0.13+1
  carousel_slider: ^2.2.1
  css_colors: ^1.0.0
  chewie: ^0.12.0
  cupertino_icons: ^1.0.0
  dotted_decoration: ^1.2.2
  # flutter_blue: ^0.7.3
  flutter_ble_lib: ^2.3.1
  flutter_html: ^1.1.1
  fluttertoast: ^5.0.1
  http: ^0.12.2
  intl: ^0.16.1
  location: ^3.0.0
  proj4dart: ^1.0.5
  shared_preferences: ^0.5.8
  system_setting: ^0.1.2
  video_player: ^1.0.1
  url_launcher: ^5.7.6
  share: ^0.6.5+4


  # assets_audio_player: ^2.0.14
  # carousel_slider: ^3.0.0
  # css_colors: ^1.1.0
  # chewie: ^1.0.0
  # cupertino_icons: ^1.0.2
  # dotted_decoration: ^1.2.2
  # # flutter_blue: ^0.7.3
  # flutter_ble_lib: ^2.3.2
  # flutter_html: ^1.0.0
  # fluttertoast: ^7.1.8
  # http: ^0.12.2
  # http_parser: ^3.1.4
  # intl: ^0.17.0
  # location: ^4.1.1
  # location_web: ^3.0.0
  # proj4dart: ^1.0.5
  # shared_preferences: ^2.0.3
  # system_setting: ^0.1.3
  # video_player: ^2.0.0
  # url_launcher: ^6.0.2
  # share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

module:
  androidX: true